# --- General ---
baseURL = "https://pabloagn.com"
languageCode = "en-us"
title = "Pablo Aguirre"

# --- Build Settings ---
buildDrafts = false
buildFuture = false
buildExpired = false
enableGitInfo = true
enableRobotsTXT = true

# --- Output Formats ---
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS"]

[pagination]
pagerSize = 12

# --- Menu Configuration ---
[menu]
[[menu.main]]
name = "Projects"
url = "/projects/"
weight =10

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 20

[[menu.main]]
name = "Deep Dives"
url = "/deep-dives/"
weight = 30

[[menu.main]]
name = "Tools"
url = "/tools/"
weight = 40

[[menu.main]]
name = "About"
url = "/about/"
weight = 60

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 70

# --- Site Parameters ---
[params]
description = "Pablo Aguirre • Elegant Development"
author = "Pablo Aguirre"
email = "pabloaguirrenck@protonmail.ch"

# --- Social Links ---
[params.social]
github = "pabloagn"
linkedin = "pablo-aguirre-nunez"

# --- Ajax Search Engine ---
[params.search]
types = ["blog", "deep-dives", "projects", "tools"]

# --- Markup Configuration ---
[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
table = true
strikethrough = true
linkify = true
taskList = true

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = false

[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = false
codeFences = true
guessSyntax = true
tabWidth = 2
