# --- General ---
baseURL = "https://pabloagn.com"
languageCode = "en-us"
title = "Pablo Aguirre"
# theme = "kanso"

# --- Build Settings ---
buildDrafts = false
buildFuture = false
buildExpired = false
enableGitInfo = true
enableRobotsTXT = true

# --- Output Formats ---
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS"]

# --- Pagination ---
paginate = 10
paginatePath = "page"

# --- Menu Configuration ---
[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 10

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 20

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 30

[[menu.main]]
name = "Deep Dives"
url = "/deepdives/"
weight = 40

# --- Site Parameters ---
[params]
description = "Pablo Aguirre • Elegant Development"
author = "Pablo Aguirre"
email = "pabloaguirrenck@protonmail.ch"

# --- Social Links ---
[params.social]
github = "pabloagn"

# --- Markup Configuration ---
[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
table = true
strikethrough = true
linkify = true
taskList = true

[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = false

[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = false
codeFences = true
guessSyntax = true
tabWidth = 2
