baseURL = "https://pabloagn.com"
languageCode = "en-us"
title = "Pablo Aguirre"
# theme = "kanso"

# Directory structure
contentDir = "src/content"
layoutDir = "src/layouts"
staticDir = "src/static"
assetDir = "src/assets"

# Build settings
buildDrafts = false
buildFuture = false
buildExpired = false
enableGitInfo = true
enableRobotsTXT = true

# Output formats
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS"]

# Taxonomies
[taxonomies]
category = "categories"
tag = "tags"
technology = "technologies"
difficulty = "difficulty"

# Pagination
paginate = 10
paginatePath = "page"

# Menu configuration
[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 10

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 20

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 30

[[menu.main]]
name = "Deep Dives"
url = "/deepdives/"
weight = 40

# Site parameters
[params]
description = "Pablo Aguirre • Elegant Development"
author = "Pablo Aguirre"
email = "pabloaguirrenck@protonmail.ch"

# Social links (customize as needed)
[params.social]
github = "pabloagn"

# Markup configuration
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions]
table = true
strikethrough = true
linkify = true
taskList = true
[markup.highlight]
style = "github-dark"
lineNos = false
lineNumbersInTable = false
tabWidth = 2
codeFences = true
guessSyntax = false
