name: Update Language Stats

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false  # ⬅️ disables default GitHub token

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Generate language stats
        run: node scripts/generate-langstats.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit if changed
        env:
          GH_PAT: ${{ secrets.GH_LANGS }}
        run: |
          git config user.name "LangStats Bot"
          git config user.email "bot@localhost"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/pabloagn/personal-website.git
          git add data/langstats/
          git diff --cached --quiet || (
            git commit -m "BOT: Update language stats"
            git push origin HEAD:main
          )

